apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  accessModes:
  - ReadWriteOnce # Other options include ReadWriteMany and ReadOnlyOnce
  storageClassName: managed-premium-retain-sc
  resources:
    requests:
      storage: 5Gi      